version: "3.1"

services:
  fastify-app:
    build: .
    container_name: fastify_app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - DB_NAME=${DB_NAME}
      - HOST=${HOST}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - app_network

  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge